set OUTBOUND_DIRECTORY=d:/oratech/outbound/
set DB_SERVER=5.39.178.94
set DB_PORT=1521
set DB_SID= oratech
set DB_USERNAME=ORATECHLIVE
set DB_PASSWORD=ORATECHLIVE
set DATA_FREQUENCY=3600
set QTYINSTOCK_FREQUENCY=300